service: sf-assignment-pow
frameworkVersion: '4'
configValidationMode: error

provider:
  name: aws
  # Latest environment supported by serverless-offline
  runtime: nodejs22.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  memorySize: 1024
  logRetentionInDays: 14
  timeout: 29

plugins:
  - serverless-offline

custom:
  esbuild:
    packager: yarn
    minify: false
    sourcemap: false
    target: node16
    watch:
      pattern: 'src/**/*.ts'

functions:
  graphql:
    handler: src/fn_graphql.handler
    events:
      - httpApi: '*'
